modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "vision_goggles"
version = "${version}"
displayName = "Vision Goggles"
authors = "ItsRealPerson"
description = '''

'''
logoFile = "icon.png"

[[dependencies.vision_goggles]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.118,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "curios"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
