# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.1.3-Alpha
maven_group=dev.itsrealperson
archives_name=vision-goggles
neoforge_version=20.4.237
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.20.4
# Dependencies
architectury_api_version=11.1.17
accessories_version=1.0.0-alpha.25+1.20.4
cloth_config_version=13.0.121
mod_menu_version=9.0.0
fabric_loader_version=0.15.11
fabric_api_version=0.97.0+1.20.4

