modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "vision_goggles"
version = "${version}"
displayName = "Vision Goggles"
authors = "ItsRealPerson"
description = '''
Vision Goggles Mod
'''
logoFile = "icon.png"

[[dependencies.vision_goggles]]
modId = "neoforge"
mandatory = true
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vision_goggles]]
modId = "cloth_config"
mandatory = true
versionRange = "[13.0.121,)"
ordering = "NONE"
side = "BOTH"